# Generated by Django 5.2.7 on 2025-10-31 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodlog',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Food Log', 'verbose_name_plural': 'Food Logs'},
        ),
        migrations.AddField(
            model_name='foodlog',
            name='nutrition_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20),
        ),
    ]
