# Generated by Django 5.2.7 on 2025-11-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_foodlog_options_foodlog_nutrition_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Food Log', 'verbose_name_plural': 'Food Logs'},
        ),
        migrations.AddField(
            model_name='foodlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
